### ISSUE TITLE
Game Client

### ISSUE THREAD

**Issue by Liming2003hit** [Zoey76/L2#8]
Thank you for your outstanding contribution.
How can I get the game client corresponding to this L2J Server?
Is there any website that can provide it?

**Comment by nightw0lv** [comment]
its for all clients that have not been cracked and contain in their system files the l2.bin, i would recommend to obfuscate the builded .exe file cause it can be dissasembled very easy, adding layers of protection making it not worth the time for an attacker is in most cases a win.

**Comment by Liming2003hit** [comment]
so my question is, where on earth can I find a client that has not been cracked?

**Comment by Zoey76** [comment]
You can get it by joining [Discord](https://discord.gg/HyE2VfY) and heading to the game client channel, there is a pinned message with such information.
