### ISSUE TITLE
What the point?

### ISSUE THREAD

**Issue by crwg** [Zoey76/L2#9]
I wanted to ask, what’s the point? You’re yelling everywhere on forum that "You can’t modify the client!!! Ohhh No!!! Don't do this!!!", but at the same time you’re posting a launch file that’s supposed to be placed in the game directory? In the same time client still won’t start without disabling gameguard, and how to disable it is a strict prohibition, you can’t even discuss it. You are doing complete nonsense, honestly. Despite the fact that you are cutting a project for a client who is so banned everywhere (HF), it cannot even be installed using standard methods in Windows. I don’t have words to describe what a mess is going on in the heads of those who making this project

Also : Ohhhh noo!!! You shared modified exe file for client!!!! Nooooo!!!! :O

**Comment by Zoey76** [comment]
Hello there, basically you are right, the original idea was to change the behavior of the game client without modifying the files, I never continued exploring this idea, I know of others who were successful with this task.

I don't get what you mean by the client being banned everywhere, if you are referring to the project being stuck in HF, I invite you to our Discord server to discuss how to move forward.
